BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Pets" (
	"petId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT,
	"species"	INTEGER NOT NULL,
	"size"	REAL NOT NULL,
	"color"	TEXT NOT NULL COLLATE NOCASE,
	"location"	INTEGER NOT NULL,
	"state"	INTEGER NOT NULL,
	"user"	INTEGER NOT NULL,
	FOREIGN KEY("user") REFERENCES "Users"("userId"),
	FOREIGN KEY("state") REFERENCES "PetState"("petStetId"),
	FOREIGN KEY("species") REFERENCES "Species"("specieId")
);
CREATE TABLE IF NOT EXISTS "Users" (
	"userId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT NOT NULL,
	"EmailAddress"	TEXT NOT NULL UNIQUE COLLATE NOCASE,
	"userName"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL CHECK(length(password)>=8)
);
CREATE TABLE IF NOT EXISTS "Queries" (
	"queryId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"specie"	INTEGER,
	"sizeTopLimit"	REAL,
	"sizeBottomLimit"	REAL,
	"color"	TEXT,
	"location"	INTEGER,
	"state"	INTEGER,
	"gender"	TEXT,
	FOREIGN KEY("state") REFERENCES "PetState"("petStetId"),
	FOREIGN KEY("specie") REFERENCES "Species"("specieId")
);
CREATE TABLE IF NOT EXISTS "PetState" (
	"petStetId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"state"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "Answers" (
	"answerId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"answerTxt"	TEXT NOT NULL,
	"question"	INTEGER NOT NULL,
	"date"	TEXT NOT NULL,
	"author"	INTEGER NOT NULL,
	FOREIGN KEY("author") REFERENCES "Users"("userId"),
	FOREIGN KEY("question") REFERENCES "Questions"("questionId")
);
CREATE TABLE IF NOT EXISTS "Questions" (
	"questionId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"questionTxt"	TEXT NOT NULL,
	"pet"	INTEGER NOT NULL,
	"date"	TEXT,
	FOREIGN KEY("pet") REFERENCES "Pets"("petId")
);
CREATE TABLE IF NOT EXISTS "Species" (
	"specieId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"specie"	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "FavouriteLists" (
	"listId"	INTEGER NOT NULL,
	"user"	INTEGER NOT NULL,
	"pet"	INTEGER NOT NULL,
	FOREIGN KEY("pet") REFERENCES "Pets"("petId"),
	PRIMARY KEY("listId"),
	FOREIGN KEY("user") REFERENCES "Users"("userId")
);
CREATE TABLE IF NOT EXISTS "Proposals" (
	"proposalId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user"	INTEGER NOT NULL,
	"pet"	INTEGER NOT NULL,
	"state"	INTEGER NOT NULL,
	FOREIGN KEY("user") REFERENCES "Users"("userId"),
	FOREIGN KEY("pet") REFERENCES "Pets"("petId"),
	UNIQUE("user","pet")
);
CREATE TABLE IF NOT EXISTS "Photos" (
	"photoId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"path"	TEXT NOT NULL UNIQUE,
	"pet"	INTEGER NOT NULL,
	FOREIGN KEY("pet") REFERENCES "Pets"("petId")
);
COMMIT;
